### ISSUE TITLE
Test 'Can create a registry with multiple controllers' is skipped.

### ISSUE THREAD

**Issue by bddap** [docknetwork/sdk#125]

**Comment by bddap** [comment]
This feature is supported by the node. https://github.com/docknetwork/dock-substrate/blob/42ecfdf2d0efd358857aa720a09194bc8b90379d/runtime/src/revoke.rs#L902

**Comment by SamHellawell** [comment]
Test now passes, perhaps was a previous implementation bug or polkadot issue when first implementing.

**Comment by SamHellawell** [comment]
Test is flaky, fails 50% of the time with badproof error. Still needs more investigation
