### ISSUE TITLE
community contacts

### ISSUE THREAD

**Issue by ski** [docknetwork/sdk#143]
Hi

Is the dock network riot channel the best way to ask questions? I have been using dock for about a month now and mostly educating myself by looking at the source code of both the substrate runtime and the javascript api. I do one burning question.  It seems to me that anyone with a did can sign a schema and persist it on the chain. I have also been able to write the same schema multiple times to the chain. Is this by design? I was wondering if it makes sense to impose costs to this operation or perhaps protect this operation using the democracy pallet, or perhaps even sudo.

**Comment by lovesh** [comment]
Hi.

> Is the dock network riot channel the best way to ask questions?

Yes.

> I have also been able to write the same schema multiple times to the chain. Is this by design?

Yes, only the id is supposed to be unique.

> I was wondering if it makes sense to impose costs to this operation

There is a cost which comprises of a fixed cost and cost depending on the length of schema. You can compare the balance of the account before and after the schema write to see the difference. If using the SDK
```
const dock = new DockAPI();
dock.init(......
const { data: balance } = await dock.api.query.system.account(account);
onsole.log(`Balance is ${balance.free}`);
```
This fee is not accurate however and will change (increase) soon once we do the benchmarking for txns.

> perhaps protect this operation using the democracy pallet, or perhaps even sudo.

This operation is intended to be done by anyone having a DID so protecting by democracy and sudo does not make sense.

**Comment by lovesh** [comment]
Hi @ski 

Does the above answer help? Do you mind sharing your use case?

**Comment by ski** [comment]
Hi @lovesh , I am using dock as a self sovereign identity provider in a p2p network by implementing parts of ethereum naming service spec https://eips.ethereum.org/EIPS/eip-137 using dids instead of raw substrate addresses.
