### ISSUE TITLE
Phase out vc-js library

### ISSUE THREAD

**Issue by SamHellawell** [docknetwork/sdk#180]
We basically started it ourselves, we do half and vc-js does other half. It's basically a wrapper around jsonld-signatures anyway, so I feel like we can replicate the functionality and maintain it better ourselves. It will be better speed wise (barely noticeable but still removes unused calls/code) and will decrease bundle size/resolve some deps issues

**Comment by bddap** [comment]
Argument for phasing out vc-js:

Vc js [dereferences properties by name](https://github.com/digitalbazaar/vc-js/blob/b5985f8e28a4cf60ac8933b47ba1cbd576de7b68/lib/vc.js#L405) which may not have the same meaning as dereferencing them by absolute URL.
