### ISSUE TITLE
Can not get testnet Token from faucet

### ISSUE THREAD

**Issue by Wangmmx** [docknetwork/sdk#219]
I entered my test address and obtained the test currency from https://faucet.dock.io/. Then the transaction was opened on the Polkadot browser and found that the value was 0. I did not receive any test currency. 
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fdanforth-1.dock.io#/explorer/query/0xea49906713cfe0dbc1ae1f67aaaa215336b1da80ea456e2fc72f2389e2461401

By the way, does the dock have its own browser? The testnet token is called Unit? So the mainnet coin is DCK, right? Isn't it the same as ERC20Token DOCK? So how to get the mainnet coin DCK?

**Comment by lovesh** [comment]
I don't know why the Polkadot broswer is showing 0, maybe our types aren't updated there but not sure. You can check it over here https://fe.dock.io/?rpc=wss%3A%2F%2Fdanforth-1.dock.io#/explorer/query/3077268, the same block.

> By the way, does the dock have its own browser?

Yes, https://fe.dock.io


> The testnet token is called Unit? So the mainnet coin is DCK, right? Isn't it the same as ERC20Token DOCK?

The testnet balances are test currency, have no real-world value, and don't correspond to ERC-20.

> So how to get the mainnet coin DCK?

If you have Dock ERC-20, you can swap it for mainnet tokens using instructions [here](https://docs.dock.io/token-migration/migration-tutorial) or you can buy from Kucoin exchange. More exchanges will be supporting soon.

**Comment by Wangmmx** [comment]
Thank you so much! Solved my big problem! OK, I will swap some DCKs
