### ISSUE TITLE
Can this SDK be replaced by Polkadot-JS/API?

### ISSUE THREAD

**Issue by Yangxin-GG** [docknetwork/sdk#220]
Excuse me , Can I use polkadot-JS/API instead of this SDK to interact with node ?

**Comment by lovesh** [comment]
Yes, SDK wraps polkadot-js as seen [here](https://github.com/docknetwork/sdk/blob/master/src/api.js#L80). For some basic operations, you can see polkadot-js directly being used [here](https://github.com/docknetwork/sdk/blob/master/src/utils/chain-ops.js).

**Comment by Yangxin-GG** [comment]
thank you
