### ISSUE TITLE
How to calculate fee in transaction body

### ISSUE THREAD

**Issue by Wangmmx** [docknetwork/sdk#222]
The fees I initiated with the web wallet are all 2.045DCK. And I observed that the transactions on the chain are all the same fees now. Is the fee fixed? If it is not fixed, how to calculate fee? 

Thanks! Looking forward to your reply

**Comment by Wangmmx** [comment]
By the way,  If the recipient is a new account, does it also require extra handling fees to create an account?

**Comment by lovesh** [comment]
> The fees I initiated with the web wallet are all 2.045DCK. And I observed that the transactions on the chain are all the same fees now. Is the fee fixed?

No, it depends on the resources consumed by the transaction, i.e. txn size, CPU time, storage, etc. As most of the transfers (to existing accounts) consume the same resources, currently the only difference will be due to size. Try transferring a large amount like 2-3 Million even if you don't have that amount and before submission, you will see the fee and it would be slightly more. Txn fees is largely determined by a Substrate concept called [weight](https://substrate.dev/docs/en/knowledgebase/learn-substrate/weight).

> If it is not fixed, how to calculate fee?

You will see the fees before you are trying to submit txn in the UI. For programmatically, you can use `paymentInfo` on the created txn as [here](https://github.com/docknetwork/sdk/blob/master/scripts/txn-pricing.js#L164) which will show the (approx.) weight and fee of the txn.

> If the recipient is a new account, does it also require extra handling fees to create an account?

Yes.

**Comment by Wangmmx** [comment]
Oh, I understand,  thanks a lot!
I just tried it on the browser, and indeed the fee has changed. When the transfer amount is large, the fee will be higher. 

Yesterday, I used offline-signing to construct the transaction and the transfer was successful. Fee was gave a larger value. I want to try to give a certain fee to the transaction body. I will check the `paymentInfo` you mentioned. Is there a relevant interface available for this?

Today, the node cannot be connected. The main network and test network are not working. Is there a problem with the node now? I see that the browser is work, and my node is `wss://mainnet-node.dock.io`

**Comment by lovesh** [comment]
> Is there a relevant interface available for this?

Not sure what you mean, interface like in the UI?

> Today, the node cannot be connected. The main network and test network are not working. Is there a problem with the node now?

It works for me.

**Comment by Wangmmx** [comment]
> > Is there a relevant interface available for this?
> 
> Not sure what you mean, interface like in the UI?

Yes, An RPC api that get the fee directly from the node through the transaction body
> > Today, the node cannot be connected. The main network and test network are not working. Is there a problem with the node now?
> It works for me.

I keep reporting the error `Disconnected from wss://mainnet-node.dock.io: 1006:: connection failed`, it’s fine now

**Comment by Wangmmx** [comment]
It doesn't work now, did I write it wrong? This is my test demo

```
var {ApiPromise,  WsProvider} = require('@polkadot/api');

async function init() {
    var types = require('./offline-signing/types');
    var rpc =  require('./offline-signing/poa-rpc-defs');

    var api = await ApiPromise.create({
      provider: new WsProvider('wss://mainnet-node.dock.io'),
        types:  types,
        rpc,
    });

    var account = await api.query.system.account('3E3yjLh1ZJYg714r3H6gAqmfiu8beDEEz6KmeuHNupmx9HNn')
    console.log(JSON.stringify(account))
}

init();
```

And keep reporting
`2021-01-07 10:38:19          API-WS: disconnected from wss://mainnet-node.dock.io: 1006:: connection failed`
![image](https://user-images.githubusercontent.com/22836587/103844411-cf87bb80-50d4-11eb-8749-04f1e8c3e6f3.png)

**Comment by lovesh** [comment]
> Yes, An RPC api that get the fee directly from the node through the transaction body

You can use `payment.queryInfo` from [here](https://fe.dock.io/#/rpc) but it needs the extension serialized. 

> var types = require('./offline-signing/types');
    var rpc =  require('./offline-signing/poa-rpc-defs');
    
 These paths don't look correct according to the SDK. `types` and   `poa-rpc-defs` are in the root of the SDK package not the `offline-signing`.

**Comment by Wangmmx** [comment]
Ok, I probably understand the interface of fee, thanks!

This path is my local path. The two files were extracted for the convenience of testing. They were originally in the SDK folder.

**Comment by lovesh** [comment]
> This path is my local path. The two files were extracted for the convenience of testing. They were originally in the SDK folder.

The the code looks fine to me. Is the error you posted complete?

**Comment by Wangmmx** [comment]
Yes, I wrote these few lines of code to test it because the connection was suddenly broken. It started reporting errors yesterday. This is a complete error. The following error is the same :1006. I ran it again just now. This is a screenshot.

![image](https://user-images.githubusercontent.com/22836587/103879297-a0903a80-5112-11eb-998e-e3aca9de60bc.png)

**Comment by lovesh** [comment]
I am running the script as `node script_name.js` and i get this error
```
(node:1933645) UnhandledPromiseRejectionWarning: ..../poa-rpc-defs.js:1
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at init (/home/lovesh/dev/dock/client-sdk/scripts/temp.js:5:16)
    at Object.<anonymous> (/home/lovesh/dev/dock/client-sdk/scripts/temp.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

```

We use es6 and expect people to be running with babel. But for now, if you comment you the lines for RPC, it should work. Like this

```
var types = require('../src/types');
    // var rpc =  require('../src/poa-rpc-defs');

    var api = await ApiPromise.create({
      provider: new WsProvider('wss://mainnet-node.dock.io'),
        types:  types,
        // rpc,
    });
```

The only thing you will be missing out with those definitions the querying the treasury.

**Comment by Wangmmx** [comment]
I refer to the connection method here https://github.com/docknetwork/sdk/blob/8ca5cc9da38fbc7acade0c391ad99c0f42f7406b/src/api.js, both using rpc and removing rpc will report errors, I am just a file, just to connect, I don’t know Why is the connection unsuccessful

![image](https://user-images.githubusercontent.com/22836587/103888006-f8cd3980-511e-11eb-8e65-b6d67e6ba88d.png)


![image](https://user-images.githubusercontent.com/22836587/103888071-113d5400-511f-11eb-9a21-e06a2ce1eadd.png)


So sad
