### ISSUE TITLE
Implement did:key resolver as standard

### ISSUE THREAD

**Issue by SamHellawell** [docknetwork/sdk#246]

**Comment by bddap** [comment]
We could provide this as an optional resolver and support it in `defaultResolver`. Correct me if I'm wrong but IIRC `defaultResolver` is a thing we provide.

For most revolvers one might argue that its better to add it to the universal resolver an go through that. The reason `did:key` is useful without going through the universal resolver is that `did:key` is very simple, it doesn't require any setup, and does not require io.
