### ISSUE TITLE
Refactor SDK into multiple packages and monorepo

### ISSUE THREAD

**Issue by cykoder** [docknetwork/sdk#261]
Similar to how polkadot organizes things, cleaner and people can then install just what they need.

**Comment by SamHellawell** [comment]
We can leverage turborepo. Examples:
https://github.com/vercel/turbo/tree/main/examples/basic
https://github.com/skitsanos/example-monorepo-turborepo

**Comment by cykoder** [comment]
finally this issue can be closed, thanks @olegnn
