### ISSUE TITLE
getTransferExtrinsicsFromBlock Error

### ISSUE THREAD

**Issue by ygcool** [docknetwork/sdk#303]
network : testnet
FullNodeEndpoint : wss://knox-1.dock.io
block hash : 0x62919abf9a48df1a7ea819065f504d75505e16b383898355b2906efc4d254ff3
block number : 188301

network : mainnet
FullNodeEndpoint : wss://mainnet-node.dock.io
block hash : 0x070c5900391dc335367223accf8e9a825f02f0339a14178bf4cbc9b00f112b5a
block number : 11339035

code : 
```
await getTransferExtrinsicsFromBlock(api, blockNumberOrHash, 'main', true, false)
```

Error: Decoding 39f3cMz2bbVohRqhdTL3xBemi6gJNB5Rot53hNGZDKk1KuVo: Expected non-null, non-empty base58 string input

How can I resolve this error?

Thanks

**Comment by ygcool** [comment]
@SamHellawell 
SDK version: 2.2.0

<img width="511" alt="image" src="https://user-images.githubusercontent.com/16422689/183542462-a447eddb-8db3-4903-b6f6-8dd3de568b77.png">

**Comment by SamHellawell** [comment]
I have asked @lovesh to take look when he has a bit of time. In the meantime, is it possible for you to create/share a repository with example code for easier reproduction?

**Comment by lovesh** [comment]
I can reproduce this issue. Looking into it.

**Comment by lovesh** [comment]
@ygcool Can you please try again with the most recent commit `e81d20dab302a994ca247cb0f34ed37930dbfad0`?

**Comment by ygcool** [comment]
@lovesh yes, It's working.  Great, thank you!

**Comment by SamHellawell** [comment]
good to hear! will close out this issue :)
