### ISSUE TITLE
How To Run Dock Network/SDK in Visual Studio

### ISSUE THREAD

**Issue by NaaneVaruvenDhanush** [docknetwork/sdk#308]
Unable to install yarn in visual studio. How to run this code in localhost server and kindly attach the comments to run SDK in windows system. While running I am getting this issue (File D:\saranraj\09_Applications\node-v14.18.1-win-x64\yarn.ps1)

**Comment by lovesh** [comment]
Whats the issue?

Also, it seems your running nodejs version 14 but SDK requires at least version 16 as seen [here](https://github.com/docknetwork/sdk/blob/master/package.json#L11)

**Comment by NaaneVaruvenDhanush** [comment]
Thanks for your reply! Installed yarn successfully in visual studio then how to start it in developement server ( localhost server). any comments to start in localhost server.

**Comment by lovesh** [comment]
Please check the [docs](https://docknetwork.github.io/sdk/tutorials), [examples](https://github.com/docknetwork/sdk/tree/master/example) and [tests](https://github.com/docknetwork/sdk/tree/master/tests/integration).
