### ISSUE TITLE
Dock Certs Code Set up

### ISSUE THREAD

**Issue by NaaneVaruvenDhanush** [docknetwork/sdk#313]
Dock certs code is started on my local server but while clicking on issuer facing Magic SDK error and also reference name text box is there for view our credential .What is that reference name means? How to solve the Magic SDK error.
![image](https://user-images.githubusercontent.com/114411994/192971727-1468fb55-fcdc-4cf3-97af-e153c9c51661.png)

**Comment by SamHellawell** [comment]
https://magic.link/docs

Certs is unsupported/archive/reference only code now

**Comment by NaaneVaruvenDhanush** [comment]
Any latest Dock certs Code is available now as an open source.
