### ISSUE TITLE
Integration tests hang forever in CI unless --forceExit is passed to CI

### ISSUE THREAD

**Issue by bddap** [docknetwork/sdk#33]
The hang may be indicative of some underlying problem.

`--forceExit` lets us ignore the problem, but we should find the root cause so we don't end up just passing the issue on to our library users.

Task: Get the "test-integration" script from package.json working in ci without using the `--forceExit` flag.

The [--detectopenhandles](https://jestjs.io/docs/en/cli#--detectopenhandles) flag will likely help with debugging.

**Comment by lovesh** [comment]
This has been fixed now https://github.com/docknetwork/sdk/commit/3b3f2202f2c5bf63da66e6f5139bd4fb1ecc7e48
