### ISSUE TITLE
underscore import error

### ISSUE THREAD

**Issue by farwayer** [docknetwork/sdk#379]
```js
$ node index.js                                                                                       [15:24:13]
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'underscore'
Require stack:
...
```

It was removed by https://github.com/docknetwork/sdk/commit/b7fbfb4446559d61de5b7d627cdbafa7b4432aaa but is imported from `index.js` file in sdk npm package.

**Comment by lovesh** [comment]
Thanks for reporting this. This has been fixed in [this PR](https://github.com/docknetwork/sdk/pull/380).

**Comment by cykoder** [comment]
@farwayer the release 6.8.2 should have this resolved
