### ISSUE TITLE
Convenience methods

### ISSUE THREAD

**Issue by lovesh** [docknetwork/sdk#50]
This issue will be updated as more inspection is done.

Following convenience methods should be added

- [ ] Create a signed presentation from credential(s) with only 1 function and not 2 as of now. The challenge should be optional and auto generated when not passed
- [ ] Add convenience method for revocations (The PR for revocation in VCDM context has some methods)
- [ ] At several places, we create an extrinsic and then submit the extrinsic using `sendTransaction`. There should be helper functions to make this a 1 step process rather than 2 step process
*Update*: Just to clarify, I am not saying we don't allow folks to have the transaction created, but saying that we allow both.

**Comment by bddap** [comment]
I haven't tested against vcjs, but maybe "challenge" is optional in a linked data proof?
https://w3c-ccg.github.io/security-vocab/#challenge
