### ISSUE TITLE
[Security] When processing jsonld, must not assume "@context"

### ISSUE THREAD

**Issue by bddap** [docknetwork/sdk#59]
In some places, like `src/utils/vc.js`. Fields from Jsonld documents are dereferenced in a potentially incorrect way.

Examples:

```js
for (let credential of presentation.verifiableCredential) { ... }
```

```js
const regId = credential.credentialStatus.id.slice(DockRevRegQualifier.length);
```

Until this is resolved, our verifier will not be suitable for production.

**Comment by bddap** [comment]
Question: are the checks that vc-js makes sufficient to ensure '@context' is what we expect?

**Comment by bddap** [comment]
Here is an example of the kind of input we should guard against. https://tinyurl.com/ycsyzdcc

Note in the example that "credentialStatus" is reassigned a new meaning. And that "poorlyNamedProperty" is defined to mean "https://www.w3.org/2018/credentials#credentialStatus".

**Comment by SamHellawell** [comment]
>Question: are the checks that vc-js makes sufficient to ensure '@context' is what we expect?

there is context check here https://github.com/digitalbazaar/vc-js/blob/00b7297aa5b7e0e701e8a6db6fb6e98d7606ec0b/lib/vc.js#L498

credentialStatus checks here https://github.com/digitalbazaar/vc-js/blob/00b7297aa5b7e0e701e8a6db6fb6e98d7606ec0b/lib/vc.js#L555 and https://github.com/digitalbazaar/vc-js/blob/00b7297aa5b7e0e701e8a6db6fb6e98d7606ec0b/lib/vc.js#L251

**Comment by SamHellawell** [comment]
Created this PR to check context and status at certain points, since we dont always invoke vcjs. Maybe theres more places this is needed, any ideas @bddap ? https://github.com/docknetwork/sdk/pull/137

**Comment by bddap** [comment]
Looking into it. In the meantime I found this tidbit: https://github.com/json-ld/json-ld.org/issues/391#issuecomment-120099792
"Duplicate context terms are overridden using a most-recently-defined-wins mechanism."

**Comment by SamHellawell** [comment]
marking resolved as of https://github.com/docknetwork/sdk/pull/137

@bddap if any more concerns feel free to open new ticket
